# SPDX-License-Identifier: AGPL-3.0-only WITH App-Fair-Distribution-Exception
# Retain the v1 identifiers: changing them would create separate store apps.
[app]
id = "org.appfair.app.Stanza-Redux"

[app.android]
id = "org.appfair.app.Stanza_Redux"

[app.harmony]
id = "org.appfair.app.Stanza_Redux"
