# SPDX-License-Identifier: AGPL-3.0-only WITH App-Fair-Distribution-Exception
host = "https://stanza-redux.app"
locales = ["en", "ar", "de", "es", "fr", "hi", "id", "it", "ja", "ko", "pt-BR", "ru", "zh-CN"]
accent-color = "#526A58"
default-platform = "ios"
icon-effect = "raise"
